### ISSUE TITLE
Google Provider Upgrade

### ISSUE THREAD

**Issue by halbgut** [sysdiglabs/terraform-google-secure-for-cloud#78]
A new and incompatible version [(4.0.0)](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0) has been released of the `google` and `google-beta` providers. This breaks the examples in this project (see partial error output below).

My suggestion would be to quick fix this by pinning the versions like I did.

I worked around the issue by pinning the versions myself. I created a separate file next to my main (copy/pasted) sysdig terraform file called `versions.tf`:

```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.67.0"
    }
    google-beta = {
      source  = "hashicorp/google"
      version = "~> 3.67.0"
    }
  }
}
```

## Error Output

```
╷
│ Error: Missing required argument
│
│   on .terraform/modules/secure-for-cloud_example_single-project/modules/services/cloud-scanning/cloud_build_permissions.tf line 7, in resource "google_project_iam_member" "builder":
│    7: resource "google_project_iam_member" "builder" {
│
│ The argument "project" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on .terraform/modules/secure-for-cloud_example_single-project/modules/services/cloud-scanning/cloud_run.tf line 79, in resource "google_project_iam_member" "cloud_run_viewer":
│   79: resource "google_project_iam_member" "cloud_run_viewer" {
│
│ The argument "project" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on .terraform/modules/secure-for-cloud_example_single-project/modules/services/cloud-scanning/pubsub_permissions.tf line 1, in resource "google_project_iam_member" "token_creator":
│    1: resource "google_project_iam_member" "token_creator" {
│
│ The argument "project" is required, but no definition was found.
╵
```

**Comment by wideawakening** [comment]
yep, caught this with tests.. 
https://github.com/sysdiglabs/terraform-google-secure-for-cloud/pull/72#issuecomment-960947123

pinned  provider version for the moment. available in `v.7.0` release. thx for the call!
we will upgrade provider as soon as required

**Comment by wideawakening** [comment]
resolved pinned version of google provider and removed from our examples to let user customize it
